blog/urls.py
from django.urls import path
from django.conf.urls import url

from . import views

urlpatterns = [
    # path('', views.index, name='index'),
    # url('b_list', views.post_list, name='post_list'),
    url(r'^$', views.post_list, name='post_list'),

]

mysite/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls import include, url

"""mysite URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/2.0/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
urlpatterns = [
    # path('blog/', include('blog.urls')),
    url(r'', include('blog.urls')),
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
]

polls/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name = 'polls'
urlpatterns = [
    # ex: /polls/
    path('', views.IndexView.as_view(), name='index'),

    # list Class
    #  path('aaa', views.ListView.as_view(), name='list2'),

    # list Class
    path('list', views.ListView2.as_view(), name='list'),   # url 접속시 name으로 찾는다

    # list
    path('list2', views.listView),

    # ex: /polls/5/
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    # test
    path('test', views.testView),

    # ex: /polls/5/results/
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    # ex: /polls/5/vote/
    path('<int:question_id>/vote/', views.vote, name='vote'),

    path('img', views.upload_file, name='img'),

]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.utils import timezone


class Post(models.Model):
    author = models.ForeignKey('auth.User', on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    text = models.TextField()
    created_date = models.DateTimeField(
            default=timezone.now)
    published_date = models.DateTimeField(
            blank=True, null=True)

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def __str__(self):
        return self.title

polls/models.py
import datetime

from django.db import models
from django.utils import timezone
from django.conf import settings


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now

    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'

    def __str__(self):
        return self.question_text


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text


# class Player(models.Model):
#     sex = models.CharField(max_length=10)
#     ages = models.CharField(max_length=10)
#
#     def __str__(self):
#         return self.sex


class Post(models.Model):
    profile_pic = models.ImageField(upload_to="blog/profile_pic")
    # 저장경로 : MEDIA_ROOT/blog/profile_pic/xxxx.jpg 경로에 저장
    # DB필드 : 'MEDIA_URL/blog/profile_pic/xxxx.jpg' 문자열 저장
    photo = models.ImageField(blank=True, upload_to="blog/%Y/%m/%d")
# 저장경로 : MEDIA_ROOT/blog/2017/05/10/xxxx.jpg 경로에 저장
# DB필드 : 'MEDIA_URL/blog/2017/05/10/xxxx.jpg' 문자열 저장

blog/views.py
# from django.http import HttpResponse
from django.shortcuts import render
from django.utils import timezone

from .models import Post


# def index(request):
#     return HttpResponse("Hello, world. You're at the polls index.")


def post_list(request):
    posts = Post.objects.filter(published_date__lte=timezone.now()).order_by('published_date')
    return render(request, 'blog/post_list.html', {'posts': posts})

polls/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from django.utils import timezone
from django.views import generic

from .models import Question, Choice


class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """
        Return the last five published questions (not including those set to be
        published in the future).
        """
        return Question.objects.filter(
            pub_date__lte=timezone.now()
        ).order_by('-pub_date')[:5]


"""
class ListView(generic.ListView):
    template_name = 'polls/list2.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        return Question.objects.filter(
            pub_date__lte=timezone.now()
        ).order_by('-pub_date')[:5]
"""


class ListView2(generic.ListView):
    template_name = 'polls/list3.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """
            Return the last five published questions (not including those set to be
            published in the future).
            """
        return Question.objects.filter(
            pub_date__lte=timezone.now()
        ).order_by('-pub_date')[:5]


class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'


def testView(request):
    return render(request, 'polls/test.html', {})


def listView(request):
    questions = Question.objects.all()
    return render(request, 'polls/list2.html', {'questions': questions})


"""
def listView(request):
    return render(request, 'polls/list.html', {})
"""


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))


def upload_file(request):
    return render(request, 'polls/upload.html', {})

blog/templates/blog/post_list.html
<!DOCTYPE html>
{% load static %}
{% load staticfiles %}
<html lang="en">
<head>
    <meta charset="UTF-8">
        <link rel="stylesheet" href="{% static 'css/blog.css' %}">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
    <link href="//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext" rel="stylesheet" type="text/css">
    <title>Jake's blog</title>
<style>
    #a {
    color:skyblue
    }

     #b {
    color:green
    }

     #c {
    color:blue
    }

    #d {
    color:blue
    }

</style>
</head>
<body>
<h1>Blog</h1>
<div class="content container">
    <div class="row">
        <div class="col-md-8">
            {% for post in posts %}
                <div class="post">
                    <div class="date">
                        <p>published: {{ post.published_date }}</p>
                    </div>
                    <h1><a href="">{{ post.title }}</a></h1>
                    <p>{{ post.text|linebreaksbr }}</p>
                </div>
            {% endfor %}
        </div>
    </div>
</div>




</body>
</html>

polls/templates/polls/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}Simple is Better Than Complex{% endblock %}</title>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    <link href="{% static 'css/cropper.min.css' %}" rel="stylesheet">
  </head>
  <body>
    <div class="container">
      {% block content %}
      {% endblock %}
    </div>
    <script src="{% static 'js/jquery-3.1.1.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/cropper.min.js' %}"></script>
    {% block javascript %}
    {% endblock %}
  </body>
</html>

polls/templates/polls/detail.html
<!DOCTYPE html>
{% load static %}
<html lang="UTF-8">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link rel="stylesheet" type="text/css" href="{% static 'polls/detail.css' %}" />
    <link rel="stylesheet" href="{% static 'polls/css/bootstrap.css' %}">
    <script src="https://code.jquery.com/jquery-3.1.1.min.js"></script>
    <script src="{% static 'polls/js/bootstrap.js' %}"></script>  <!-- if you are typing this code upper jQuery code, it will be error -->
    <title>Title</title>
    <style>

           .form-group{
            font-size:30px;
            margin-bottom:5px;
        }

        #ggg:nth-of-type(odd){
           <!-- background-color:#f9f9f9;-->
        }

         #ggg:nth-of-type(even){
            <!--background-color:#ffffff;-->
        }

        #ggg:hover{

            background-color:#f9f9f9;
                }

         .row {
            margin-right:0;
            margin-left:0;
         }

         label {
            margin-bottom:0;
         }
    </style>
</head>
<body>
<!--detail-->

<div class="container">
	<h1 class="h1">detail</h1>
	<a href="{% url 'polls:list' %}">Home</a> > Vote > <a href="{% url 'polls:results' question.id  %}"> {{ question.question_text }} </a>
    <div class="jumbotron">
  	<h1 class="h1">{{ question.question_text }}</h1>
        <hr class="my-4">
			{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
			<form action="{% url 'polls:vote' question.id %}" method="post">
				<!--<h1>{{ question.question_text }}</h1>-->
				<!--<h3 style="text-alig : center;">SIng up</h3>-->
				{% csrf_token %}
				<!--<input type="radio" name="choice" id="choice3{{ forloop.counter }}" value="man" />-->
				<!--<label for="choice{{ forloop.counter }}">{{ choice.sex }}</label><br />-->
				<!--<input type="radio" name="choice" id="choice2{{ forloop.counter }}" value="woman" />-->
				<!--<label for="choice2{{ forloop.counter }}">{{ choice.sex }}</label><br />-->
				{% for choice in question.choice_set.all %}
			 <div class="row form-group" id="ggg">
					<input type="radio"  name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
                    	<label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label>
				</div>  <br />
				{% endfor %}
                <input type="submit" class="btn btn-primary form-control" value="Vote" >
			</form>
  </p>
</div>
</div>
</body>
</html>

polls/templates/polls/index.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}" />
<!DOCTYPE html>
<html lang="UTF-8">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<!--index-->
<h1 class="h1">index</h1>
{% if latest_question_list %}
    <div>gg</div>
    <ul>
    {% for question in latest_question_list %}
        <li><a id="a" href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
<div>ll</div>
    <p>No polls are available.</p>
{% endif %}
<a href="test">test</a>

</body>
</html>

polls/templates/polls/list.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}" />
    <link rel="stylesheet" href="{% static 'polls/css/bootstrap.css' %}">
     <script src="https://code.jquery.com/jquery-3.1.1.min.js"></script>
    <script src="{% static 'polls/js/bootstrap.js' %}"></script>
    <title>Title</title>
</head>
<body>
<h1>List</h1>
<div class="container">
	<div class="col-lg-4"></div>
	<div class="col-lg-4">
		<div class="jumbotron" style="padding-top: 20px;">
			<form method="post" action="joinAction.jsp">
				<h3 style="text-alig : center;">SIng up</h3>
				<div class="form-group">
					<input type="text" class="form-control" placeholder="ID" name="userID" maxlength="20"/>
				</div>
				<div class="form-group">
					<input type="password" class="form-control" placeholder="Password" name="userPassword" maxlength="20"/>
				</div>
				<div class="form-group">
					<input type="text" class="form-control" placeholder="Name" name="userName" maxlength="20"/>
				</div>
				<div class="form-group">
					<input type="text" class="form-control" placeholder="Email" name="userEmail" maxlength="20"/>
				</div>
				<div class="form-group" style="text-align: center;">
						<label class="btn btn-primary active">
							<input type="radio" autocomplete="off" value="man" checked name="userGender"/>man
						</label>
						<label class="btn btn-primary">
							<input type="radio" autocomplete="off" value="woman" checked name="userGender"/>woman
						</label>
				</div>
				<input type="submit" class="btn btn-primary form-control" value="Register">
			</form>
		</div>
	</div>
</div>


{% if latest_question_list %}
    <div>gg</div>
    <ul>
    {% for question in latest_question_list %}
        <li><a id="a" href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
<div>ll</div>
    <p>No polls are available.</p>
{% endif %}
</body>
</html>

polls/templates/polls/list2.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}" />
    <link rel="stylesheet" href="{% static 'polls/css/bootstrap.css' %}">
     <script src="https://code.jquery.com/jquery-3.1.1.min.js"></script>
    <script src="{% static 'polls/js/bootstrap.js' %}"></script>
    <title>Title</title>
</head>
<body>
<!-- <div class="container">
	<div class="col-lg-4"></div>
	<div class="col-lg-4">
		<div class="jumbotron" style="padding-top: 20px;">
			<form method="post" action="joinAction.jsp">
				<h3 style="text-alig : center;">SIng up</h3>
				<div class="form-group">
					<input type="text" class="form-control" placeholder="ID" name="userID" maxlength="20"/>
				</div>
				<div class="form-group">
					<input type="password" class="form-control" placeholder="Password" name="userPassword" maxlength="20"/>
				</div>
				<div class="form-group">
					<input type="text" class="form-control" placeholder="Name" name="userName" maxlength="20"/>
				</div>
				<div class="form-group">
					<input type="text" class="form-control" placeholder="Email" name="userEmail" maxlength="20"/>
				</div>
				{% for question in latest_question_list %}
				<div class="form-group" style="text-align: center; border:green 1px solid">
						<label class="btn btn-primary active" style="width:300px;">


							<li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>

						</label>
				</div>
				{% endfor %}
				<div>//////////////////////////////</div>
				{% for question in latest_question_list %}
				<div class="form-group" style="text-align: center; border:green 1px solid">
						<label class="btn btn-primary active" style="width:300px;">
							<input type="radio" autocomplete="off" value="woman" checked name="userGender"/>woman

							<li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>

						</label>
				</div>
				{% endfor %}
				<input type="submit" class="btn btn-primary form-control" value="Register">
			</form>
		</div>
	</div>
</div> -->

<!-- <h1>List2</h1>
{% if latest_question_list %}
    <div>gg</div>
    <ul>
    {% for question in latest_question_list %}
        <li><a id="a" href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
<div>ll</div>
    <p>No polls are available.</p>
{% endif %}
-->



<div class="container">
	<h1>List2</h1>
	<div class="row">
		<table class="table table-striped" style="text-align:center; border:1px solid #dddddd">
			<tr>
				<th style="background-color:#eeeeeeee; text-align:center;">Number</th>
				<th style="background-color:#eeeeeeee; text-align:center;">Subject</th>
				<th style="background-color:#eeeeeeee; text-align:center;">Date</th>
			</tr>
			<tbody>
			{% for question in questions %}
				<tr>
					<td>{{ question.id }}</td>
					<td><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></td>
					<td>{{ question.pub_date }}</td>

				</tr>
			{% endfor %}
			</tbody>
		</table>
	</div>
</div>
</body>
</html>

polls/templates/polls/list3.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static 'polls/list3.css' %}" />
    <link rel="stylesheet" href="{% static 'polls/css/bootstrap.css' %}">
     <script src="https://code.jquery.com/jquery-3.1.1.min.js"></script>
    <script src="{% static 'polls/js/bootstrap.js' %}"></script>
    <title>Title</title>
<style>

     <style>
    /**{border:skyblue solid 1px}*/

    * {
        list-style:none;
    }

    td,  {
        font-size:30px;
    }

       .form-group{
            font-size:30px;
            margin-bottom:5px;
        }

        #ggg:nth-of-type(odd){
           <!-- background-color:#f9f9f9;-->
        }

         #ggg:nth-of-type(even){
            <!--background-color:#ffffff;-->
        }

        #ggg:hover{

            background-color:#f9f9f9;
                }

         .row {
            margin-right:0;
            margin-left:0;
         }

         label {
            margin-bottom:0;
         }


     #span{
       float:right;
    }
    </style>

</style>
</head>
<body>
<div class="container">
    <h1>List</h1>
	<a href="{% url 'polls:list' %}">Home</a>


<div class="row" >
 <div class="col-sm-6 col-lg-3" style="width:100%;">
		<table class="table table-hover table-striped" style="text-align:center; border:1px solid #dddddd">
			<tr>
				<th style="background-color:#eeeeeeee; text-align:center;">Number</th>
				<th style="background-color:#eeeeeeee; text-align:center;">Subject</th>
				<th style="background-color:#eeeeeeee; text-align:center;">Date</th>
			</tr>
			<tbody>
			{% for question in latest_question_list %}
				<tr>
					<td>
                        <a href="{% url 'polls:detail' question.id %}">{{ question.id }}</a>
					</td>
					<td>

        				<li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>

					</td>
					<td>
        					{{ question.pub_date }}
    				</td>

				</tr>
			{% endfor %}
			</tbody>
		</table>
        </div>
	</div>
</div>





</body>
</html>

polls/templates/polls/photo_list.html
{% extends 'base.html' %}

{% block javascript %}
  <script>
    $(function () {

      /* SCRIPT TO OPEN THE MODAL WITH THE PREVIEW */
      $("#id_file").change(function () {
        // ...
      });

      /* SCRIPTS TO HANDLE THE CROPPER BOX */
      var $image = $("#image");
      // ...

      /* SCRIPT TO COLLECT THE DATA AND POST TO THE SERVER */
      $(".js-crop-and-upload").click(function () {
        // ...
      });

    });
  </script>
{% endblock %}

{% block content %}
  <!-- FORM TO UPLOAD THE IMAGES -->
  <form method="post" enctype="multipart/form-data" id="formUpload">
     {% csrf_token %}
  {{ form }
  </form>

  <!-- MODAL TO CROP THE IMAGE -->
  <div class="modal fade" id="modalCrop">
    ...
  </div>

  <!-- CONTAINER TO DISPLAY THE CROPPED IMAGES -->
  <div class="row" style="margin-top: 20px">
    ...
  </div>
{% endblock %}

polls/templates/polls/results.html
<!DOCTYPE html>
{% load static %}
<html lang="UTF-8">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static 'polls/detail.css' %}" />
    <link rel="stylesheet" href="{% static 'polls/css/bootstrap.css' %}">
    <title>Title</title>
    <style>
    /**{border:skyblue solid 1px}*/

       .form-group{
            font-size:30px;
            margin-bottom:5px;
        }

        #ggg:nth-of-type(odd){
           <!-- background-color:#f9f9f9;-->
        }

         #ggg:nth-of-type(even){
            <!--background-color:#ffffff;-->
        }

        #ggg:hover{

            background-color:#f9f9f9;
                }

         .row {
            margin-right:0;
            margin-left:0;
         }

         label {
            margin-bottom:0;
         }


     #span{
       float:right;
    }
    </style>
</head>
<body>
<!--results-->


<div class="container">
    <h1>results</h1>
    <a href="{% url 'polls:list' %}">Home</a> > <a href="{% url 'polls:detail' question.id  %}">Vote</a > > {{ question.question_text }}
    <div class="jumbotron">
  	<h1 class="h1">{{ question.question_text }}</h1>
        <hr class="my-4">
            {% for choice in question.choice_set.all %}
			 <div class="row form-group" id="ggg">
                 {{ choice.choice_text }}<span id="span">{{ choice.votes }} vote{{ choice.votes|pluralize }}</span>
				</div>
{% endfor %}
  <a href="{% url 'polls:detail' question.id %}" class="btn btn-primary form-control">Vote again?</a>
</div>
</div>
</body>
</html>

polls/templates/polls/test.html
<!DOCTYPE html>
{% load static %}
<html lang="UTF-8">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'polls/css/bootstrap.css' %}">
    <script src="https://code.jquery.com/jquery-3.1.1.min.js"></script>
    <script src="{% static 'polls/js/bootstrap.js' %}"></script>  <!-- if you are typing this code upper jQuery code, it will be error -->

    <title>Title</title>
</head>
<body>
<!--detail-->
<h1>test</h1>

<nav class="navbar navbar-default">
	<div class="navbar-header">
		<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
			<span class="icon-bar"></span>
			<span class="icon-bar"></span>
			<span class="icon-bar"></span>
		</button>
		<a class="navbar-brand" href="main.jsp">JSP Bulletin Board</a>
	</div>
	<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
		<ul class="nav navbar-nav">
			<li><a href="main.jsp">Main</a></li>
			<li ><a href="bbs.jsp">Bulletin Board</a></li>
		</ul>
		<ul class="nav navbar-nav navbar-right">
			<li class="dropdown">
				<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Connect<span class="caret"></span></a>
				<ul class="dropdown-menu">
					<li ><a href="login.jsp">Login</a></li>
					<li class="active"><a href="join.jsp">Sign up</a></li>
				</ul>
			</li>
		</ul>
	</div>
</nav>
<div class="container">
	<div class="col-lg-4"></div>
	<div class="col-lg-4">
		<div class="jumbotron" style="padding-top: 20px;">
			<form method="post" action="joinAction.jsp">
				<h3 style="text-alig : center;">SIng up</h3>
				<div class="form-group">
					<input type="text" class="form-control" placeholder="ID" name="userID" maxlength="20"/>
				</div>
				<div class="form-group">
					<input type="password" class="form-control" placeholder="Password" name="userPassword" maxlength="20"/>
				</div>
				<div class="form-group">
					<input type="text" class="form-control" placeholder="Name" name="userName" maxlength="20"/>
				</div>
				<div class="form-group">
					<input type="text" class="form-control" placeholder="Email" name="userEmail" maxlength="20"/>
				</div>
				<div class="form-group" style="text-align: center;">
						<label class="btn btn-primary active">
							<input type="radio" autocomplete="off" value="man" checked name="userGender"/>man
						</label>
						<label class="btn btn-primary">
							<input type="radio" autocomplete="off" value="woman" checked name="userGender"/>woman
						</label>
				</div>
				<input type="submit" class="btn btn-primary form-control" value="Register">
			</form>
		</div>
	</div>
</div>

				<input type="radio" name="choice" id="choice3{{ forloop.counter }}" value="man" />
				<label for="player{{ forloop.counter }}">{{ choice.sex }}</label><br />
				<input type="radio" name="choice" id="choice2{{ forloop.counter }}" value="woman" />
				<label for="choice2{{ forloop.counter }}">{{ choice.sex }}</label><br />

</body>
</html>

polls/templates/polls/upload.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}Simple is Better Than Complex{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'polls/css/bootstrap.css' %}">
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    <link href="{% static 'css/cropper.min.css' %}" rel="stylesheet">
    <title>Title</title>
</head>
<body>
<h1>image</h1>









<form method='post' action='' enctype="multipart/form-data">
	{% csrf_token %}
	<table>
		{{ form.as_table }}
	</table>
	<input type="submit">
</form>

<p>////////////////////</p>


<h2>{{ post.title }}</h2>
{% if post.photo %}
path :{{ post.photo.path }} # /Users/nickname/documents/practice/media/jeju_pic.png
url : {{ post.photo.url }} # /media/jeju_pic.png
<img src="{{ post.photo.url }}" alt="">
{% endif %}
</body>
</html>